"use client";

import React, { useState } from "react";
import { X, Menu, Calendar } from "lucide-react";
import LeftSidebar from "./LeftSidebar";
import RightSidebar from "./RightSidebar";
import Header from "./Header";
import EventsTable from "./event/EventsTable";

const EventsDashboard = () => {
  const [leftSidebarOpen, setLeftSidebarOpen] = useState(false);
  const [rightSidebarOpen, setRightSidebarOpen] = useState(false);
  const [currentDate, setCurrentDate] = useState(new Date(2025, 9, 1));
  const [activeTab, setActiveTab] = useState("all");
  const [calendarView, setCalendarView] = useState("month");
  const [typeFilter, setTypeFilter] = useState("Show All");
  const [sortFilter, setSortFilter] = useState("Show All");

  const events = [
    {
      id: 1,
      name: "Evening CrossFit Training",
      image:
        "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=400&h=400&fit=crop",
      banner:
        "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=1200&h=400&fit=crop",
      group: "CrossFit Warriors",
      sport: "CrossFit",
      start: "01 Nov 25",
      end: "01 Nov 25",
      created: "25 Sept 25",
      club: "Elite Fitness Club",
      eventStyle: "High Intensity",
      sportGroup: "Strength & Conditioning",
      sportName: "CrossFit",
      facility: "Downtown Sports Complex",
      salon: "Main Training Hall",
      eventLocation: "123 Main Street, Building A, Floor 2",
      eventStartDate: "2025-11-01",
      eventStartTime: "18:00",
      eventEndDate: "2025-11-01",
      eventEndTime: "20:00",
      capacity: "25",
      level: "intermediate",
      type: "training",
      priceType: "paid",
      participantFee: "50",
      equipment: "Training shoes, water bottle, towel, resistance bands",
      isPrivate: false,
      isRecurring: true,
    },
    {
      id: 2,
      name: "Morning Yoga Class",
      image:
        "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=400&h=400&fit=crop",
      banner:
        "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=1200&h=400&fit=crop",
      group: "Zen Yogis",
      sport: "Yoga",
      start: "01 Oct 25",
      end: "01 Oct 25",
      created: "25 Sept 25",
      club: "Harmony Wellness Center",
      eventStyle: "Relaxing",
      sportGroup: "Mind & Body",
      sportName: "Hatha Yoga",
      facility: "Wellness Hub",
      salon: "Studio A",
      eventLocation: "456 Peaceful Ave, 3rd Floor",
      eventStartDate: "2025-10-01",
      eventStartTime: "07:00",
      eventEndDate: "2025-10-01",
      eventEndTime: "08:30",
      capacity: "15",
      level: "beginner",
      type: "workshop",
      priceType: "paid",
      participantFee: "30",
      equipment: "Yoga mat, comfortable clothing, water",
      isPrivate: false,
      isRecurring: true,
    },
    {
      id: 3,
      name: "Basketball Tournament Finals",
      image:
        "https://images.unsplash.com/photo-1546519638-68e109498ffc?w=400&h=400&fit=crop",
      banner:
        "https://images.unsplash.com/photo-1546519638-68e109498ffc?w=1200&h=400&fit=crop",
      group: "City League",
      sport: "Basketball",
      start: "10 Sept 25",
      end: "10 Sept 25",
      created: "09 Sept 25",
      club: "Metro Basketball Association",
      eventStyle: "Competitive",
      sportGroup: "Team Sports",
      sportName: "Basketball",
      facility: "City Sports Arena",
      salon: "Court 1",
      eventLocation: "789 Sports Way, Main Arena",
      eventStartDate: "2025-09-10",
      eventStartTime: "19:00",
      eventEndDate: "2025-09-10",
      eventEndTime: "22:00",
      capacity: "500",
      level: "advanced",
      type: "tournament",
      priceType: "free",
      participantFee: "",
      equipment: "Basketball shoes, team jersey, sports drinks",
      isPrivate: false,
      isRecurring: false,
    },
    {
      id: 4,
      name: "Swimming Marathon",
      image:
        "https://images.unsplash.com/photo-1519315901367-f34ff9154487?w=400&h=400&fit=crop",
      banner:
        "https://images.unsplash.com/photo-1519315901367-f34ff9154487?w=1200&h=400&fit=crop",
      group: "Aqua Masters",
      sport: "Swimming",
      start: "11 Oct 25",
      end: "12 Oct 25",
      created: "27 Aug 25",
      club: "Olympic Pool Club",
      eventStyle: "Endurance",
      sportGroup: "Aquatic Sports",
      sportName: "Swimming",
      facility: "National Swimming Complex",
      salon: "Olympic Pool",
      eventLocation: "321 Aquatic Drive, Pool Complex",
      eventStartDate: "2025-10-11",
      eventStartTime: "06:00",
      eventEndDate: "2025-10-12",
      eventEndTime: "18:00",
      capacity: "100",
      level: "professional",
      type: "competition",
      priceType: "paid",
      participantFee: "75",
      equipment: "Swimming cap, goggles, swimsuit, towel",
      isPrivate: false,
      isRecurring: false,
    },
    {
      id: 5,
      name: "Private Tennis Coaching",
      image:
        "https://images.unsplash.com/photo-1554068865-24cecd4e34b8?w=400&h=400&fit=crop",
      banner:
        "https://images.unsplash.com/photo-1554068865-24cecd4e34b8?w=1200&h=400&fit=crop",
      group: "Elite Tennis Academy",
      sport: "Tennis",
      start: "15 Nov 25",
      end: "15 Dec 25",
      created: "01 Oct 25",
      club: "Premier Tennis Club",
      eventStyle: "One-on-One",
      sportGroup: "Racket Sports",
      sportName: "Tennis",
      facility: "Tennis Excellence Center",
      salon: "Private Court 3",
      eventLocation: "555 Tennis Boulevard, Indoor Courts",
      eventStartDate: "2025-11-15",
      eventStartTime: "14:00",
      eventEndDate: "2025-12-15",
      eventEndTime: "16:00",
      capacity: "5",
      level: "advanced",
      type: "training",
      priceType: "paid",
      participantFee: "200",
      equipment: "Tennis racket, tennis shoes, sports attire, water bottle",
      isPrivate: true,
      isRecurring: true,
    },
    {
      id: 6,
      name: "Community Running Event",
      image:
        "https://images.unsplash.com/photo-1552674605-db6ffd4facb5?w=400&h=400&fit=crop",
      banner:
        "https://images.unsplash.com/photo-1552674605-db6ffd4facb5?w=1200&h=400&fit=crop",
      group: "City Runners",
      sport: "Running",
      start: "20 Oct 25",
      end: "20 Oct 25",
      created: "15 Sept 25",
      club: "Runners United",
      eventStyle: "Social",
      sportGroup: "Track & Field",
      sportName: "5K Run",
      facility: "City Park",
      salon: "",
      eventLocation: "Central Park, Main Entrance, Track Area",
      eventStartDate: "2025-10-20",
      eventStartTime: "08:00",
      eventEndDate: "2025-10-20",
      eventEndTime: "10:00",
      capacity: "300",
      level: "beginner",
      type: "social",
      priceType: "donation",
      participantFee: "10",
      equipment: "Running shoes, comfortable sportswear, water",
      isPrivate: false,
      isRecurring: false,
    },
    {
      id: 7,
      name: "Boxing Championship",
      image:
        "https://images.unsplash.com/photo-1549719386-74dfcbf7dbed?w=400&h=400&fit=crop",
      banner:
        "https://images.unsplash.com/photo-1549719386-74dfcbf7dbed?w=1200&h=400&fit=crop",
      group: "Fight Club Pro",
      sport: "Boxing",
      start: "05 Dec 25",
      end: "05 Dec 25",
      created: "20 Oct 25",
      club: "Champions Boxing Gym",
      eventStyle: "Competitive",
      sportGroup: "Combat Sports",
      sportName: "Boxing",
      facility: "Combat Sports Arena",
      salon: "Main Ring",
      eventLocation: "888 Fighter's Way, Arena Building",
      eventStartDate: "2025-12-05",
      eventStartTime: "19:00",
      eventEndDate: "2025-12-05",
      eventEndTime: "23:00",
      capacity: "200",
      level: "professional",
      type: "competition",
      priceType: "paid",
      participantFee: "100",
      equipment: "Boxing gloves, hand wraps, mouthguard, protective gear",
      isPrivate: false,
      isRecurring: false,
    },
    {
      id: 8,
      name: "Pilates Workshop",
      image:
        "https://images.unsplash.com/photo-1518611012118-696072aa579a?w=400&h=400&fit=crop",
      banner:
        "https://images.unsplash.com/photo-1518611012118-696072aa579a?w=1200&h=400&fit=crop",
      group: "Core Strength Society",
      sport: "Pilates",
      start: "12 Nov 25",
      end: "12 Nov 25",
      created: "28 Sept 25",
      club: "Body Balance Studio",
      eventStyle: "Instructional",
      sportGroup: "Mind & Body",
      sportName: "Pilates",
      facility: "Wellness Studio",
      salon: "Room B",
      eventLocation: "234 Wellness Street, 2nd Floor Studio",
      eventStartDate: "2025-11-12",
      eventStartTime: "10:00",
      eventEndDate: "2025-11-12",
      eventEndTime: "12:00",
      capacity: "20",
      level: "intermediate",
      type: "workshop",
      priceType: "paid",
      participantFee: "40",
      equipment: "Pilates mat, resistance bands, comfortable clothing",
      isPrivate: true,
      isRecurring: true,
    },
    {
      id: 9,
      name: "Youth Soccer Camp",
      image:
        "https://images.unsplash.com/photo-1551958219-acbc608c6377?w=400&h=400&fit=crop",
      banner:
        "https://images.unsplash.com/photo-1551958219-acbc608c6377?w=1200&h=400&fit=crop",
      group: "Junior Stars FC",
      sport: "Soccer",
      start: "25 Oct 25",
      end: "29 Oct 25",
      created: "10 Sept 25",
      club: "Youth Sports Academy",
      eventStyle: "Educational",
      sportGroup: "Team Sports",
      sportName: "Soccer",
      facility: "Academy Sports Field",
      salon: "Field 2",
      eventLocation: "999 Youth Sports Lane, Training Grounds",
      eventStartDate: "2025-10-25",
      eventStartTime: "09:00",
      eventEndDate: "2025-10-29",
      eventEndTime: "15:00",
      capacity: "50",
      level: "beginner",
      type: "training",
      priceType: "paid",
      participantFee: "150",
      equipment: "Soccer cleats, shin guards, water bottle, sunscreen",
      isPrivate: false,
      isRecurring: false,
    },
    {
      id: 10,
      name: "Cycling Adventure",
      image:
        "https://images.unsplash.com/photo-1541625602330-2277a4c46182?w=400&h=400&fit=crop",
      banner:
        "https://images.unsplash.com/photo-1541625602330-2277a4c46182?w=1200&h=400&fit=crop",
      group: "Mountain Riders",
      sport: "Cycling",
      start: "18 Nov 25",
      end: "18 Nov 25",
      created: "05 Oct 25",
      club: "Adventure Cycling Club",
      eventStyle: "Outdoor",
      sportGroup: "Outdoor Sports",
      sportName: "Mountain Biking",
      facility: "",
      salon: "",
      eventLocation: "Mountain Trail Park, North Entrance, Trail Head",
      eventStartDate: "2025-11-18",
      eventStartTime: "07:00",
      eventEndDate: "2025-11-18",
      eventEndTime: "14:00",
      capacity: "30",
      level: "intermediate",
      type: "social",
      priceType: "free",
      participantFee: "",
      equipment: "Mountain bike, helmet, gloves, water, snacks, first aid kit",
      isPrivate: false,
      isRecurring: true,
    },
    {
      id: 11,
      name: "Volleyball Beach Tournament",
      image:
        "https://images.unsplash.com/photo-1612872087720-bb876e2e67d1?w=400&h=400&fit=crop",
      banner:
        "https://images.unsplash.com/photo-1612872087720-bb876e2e67d1?w=1200&h=400&fit=crop",
      group: "Beach Warriors",
      sport: "Volleyball",
      start: "22 Nov 25",
      end: "22 Nov 25",
      created: "12 Oct 25",
      club: "Coastal Sports Club",
      eventStyle: "Competitive",
      sportGroup: "Team Sports",
      sportName: "Beach Volleyball",
      facility: "Sunny Beach Arena",
      salon: "Beach Court 1",
      eventLocation: "Sunset Beach, Court Area 3",
      eventStartDate: "2025-11-22",
      eventStartTime: "10:00",
      eventEndDate: "2025-11-22",
      eventEndTime: "18:00",
      capacity: "64",
      level: "intermediate",
      type: "tournament",
      priceType: "paid",
      participantFee: "35",
      equipment: "Beach volleyball, sunscreen, sports attire, water",
      isPrivate: false,
      isRecurring: false,
    },
    {
      id: 12,
      name: "Martial Arts Seminar",
      image:
        "https://images.unsplash.com/photo-1555597673-b21d5c935865?w=400&h=400&fit=crop",
      banner:
        "https://images.unsplash.com/photo-1555597673-b21d5c935865?w=1200&h=400&fit=crop",
      group: "Dojo Masters",
      sport: "Martial Arts",
      start: "28 Oct 25",
      end: "28 Oct 25",
      created: "18 Sept 25",
      club: "Elite Martial Arts Academy",
      eventStyle: "Educational",
      sportGroup: "Combat Sports",
      sportName: "Karate",
      facility: "Martial Arts Center",
      salon: "Main Dojo",
      eventLocation: "1122 Fighter Street, Dojo Building",
      eventStartDate: "2025-10-28",
      eventStartTime: "09:00",
      eventEndDate: "2025-10-28",
      eventEndTime: "17:00",
      capacity: "40",
      level: "advanced",
      type: "workshop",
      priceType: "paid",
      participantFee: "80",
      equipment: "Gi, belt, protective gear, water bottle",
      isPrivate: false,
      isRecurring: false,
    },
    {
      id: 13,
      name: "Indoor Rock Climbing Session",
      image:
        "https://images.unsplash.com/photo-1522163182402-834f871fd851?w=400&h=400&fit=crop",
      banner:
        "https://images.unsplash.com/photo-1522163182402-834f871fd851?w=1200&h=400&fit=crop",
      group: "Vertical Limits",
      sport: "Rock Climbing",
      start: "08 Nov 25",
      end: "08 Nov 25",
      created: "25 Sept 25",
      club: "Summit Climbing Gym",
      eventStyle: "Adventure",
      sportGroup: "Extreme Sports",
      sportName: "Indoor Climbing",
      facility: "Peak Climbing Center",
      salon: "Main Wall",
      eventLocation: "334 Adventure Way, Climbing Hall",
      eventStartDate: "2025-11-08",
      eventStartTime: "14:00",
      eventEndDate: "2025-11-08",
      eventEndTime: "18:00",
      capacity: "20",
      level: "beginner",
      type: "training",
      priceType: "paid",
      participantFee: "45",
      equipment: "Climbing shoes, harness, chalk bag (provided)",
      isPrivate: false,
      isRecurring: true,
    },
    {
      id: 14,
      name: "Spin Class Intensive",
      image:
        "https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=400&h=400&fit=crop",
      banner:
        "https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=1200&h=400&fit=crop",
      group: "Spin Masters",
      sport: "Spinning",
      start: "03 Nov 25",
      end: "03 Nov 25",
      created: "20 Sept 25",
      club: "Revolution Fitness",
      eventStyle: "High Energy",
      sportGroup: "Cardio",
      sportName: "Indoor Cycling",
      facility: "Revolution Studio",
      salon: "Spin Room A",
      eventLocation: "445 Fitness Street, Studio Level",
      eventStartDate: "2025-11-03",
      eventStartTime: "06:30",
      eventEndDate: "2025-11-03",
      eventEndTime: "07:30",
      capacity: "30",
      level: "intermediate",
      type: "training",
      priceType: "paid",
      participantFee: "25",
      equipment: "Water bottle, towel, cycling shoes optional",
      isPrivate: false,
      isRecurring: true,
    },
    {
      id: 15,
      name: "Golf Championship",
      image:
        "https://images.unsplash.com/photo-1535131749006-b7f58c99034b?w=400&h=400&fit=crop",
      banner:
        "https://images.unsplash.com/photo-1535131749006-b7f58c99034b?w=1200&h=400&fit=crop",
      group: "Green Eagles",
      sport: "Golf",
      start: "14 Dec 25",
      end: "15 Dec 25",
      created: "01 Nov 25",
      club: "Royal Golf Club",
      eventStyle: "Competitive",
      sportGroup: "Precision Sports",
      sportName: "Golf",
      facility: "Royal Golf Course",
      salon: "",
      eventLocation: "Royal Golf Estate, Main Course",
      eventStartDate: "2025-12-14",
      eventStartTime: "08:00",
      eventEndDate: "2025-12-15",
      eventEndTime: "17:00",
      capacity: "120",
      level: "professional",
      type: "competition",
      priceType: "paid",
      participantFee: "250",
      equipment: "Golf clubs, golf balls, tees, golf shoes, glove",
      isPrivate: true,
      isRecurring: false,
    },
    {
      id: 16,
      name: "Dance Fitness Party",
      image:
        "https://images.unsplash.com/photo-1518611012118-696072aa579a?w=400&h=400&fit=crop",
      banner:
        "https://images.unsplash.com/photo-1518611012118-696072aa579a?w=1200&h=400&fit=crop",
      group: "Dance Vibes",
      sport: "Dance",
      start: "07 Nov 25",
      end: "07 Nov 25",
      created: "22 Sept 25",
      club: "Rhythm Studio",
      eventStyle: "Fun",
      sportGroup: "Dance",
      sportName: "Zumba",
      facility: "Dance Studio Pro",
      salon: "Studio 2",
      eventLocation: "567 Dance Avenue, 3rd Floor",
      eventStartDate: "2025-11-07",
      eventStartTime: "19:00",
      eventEndDate: "2025-11-07",
      eventEndTime: "20:30",
      capacity: "35",
      level: "beginner",
      type: "social",
      priceType: "donation",
      participantFee: "15",
      equipment: "Comfortable clothing, dance shoes, water",
      isPrivate: false,
      isRecurring: true,
    },
    {
      id: 17,
      name: "Triathlon Sprint",
      image:
        "https://images.unsplash.com/photo-1476480862126-209bfaa8edc8?w=400&h=400&fit=crop",
      banner:
        "https://images.unsplash.com/photo-1476480862126-209bfaa8edc8?w=1200&h=400&fit=crop",
      group: "Iron Warriors",
      sport: "Triathlon",
      start: "30 Nov 25",
      end: "30 Nov 25",
      created: "15 Oct 25",
      club: "Tri-State Athletics",
      eventStyle: "Endurance",
      sportGroup: "Multi-Sport",
      sportName: "Triathlon",
      facility: "City Sports Complex",
      salon: "",
      eventLocation: "Lakeside Park, Multi-Sport Area",
      eventStartDate: "2025-11-30",
      eventStartTime: "07:00",
      eventEndDate: "2025-11-30",
      eventEndTime: "12:00",
      capacity: "150",
      level: "advanced",
      type: "competition",
      priceType: "paid",
      participantFee: "120",
      equipment: "Bike, helmet, swimsuit, running shoes, transition gear",
      isPrivate: false,
      isRecurring: false,
    },
    {
      id: 18,
      name: "Badminton Club Night",
      image:
        "https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?w=400&h=400&fit=crop",
      banner:
        "https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?w=1200&h=400&fit=crop",
      group: "Shuttle Masters",
      sport: "Badminton",
      start: "16 Nov 25",
      end: "16 Nov 25",
      created: "30 Sept 25",
      club: "Racket Club",
      eventStyle: "Social",
      sportGroup: "Racket Sports",
      sportName: "Badminton",
      facility: "Indoor Sports Hall",
      salon: "Courts 1-4",
      eventLocation: "778 Sports Drive, Indoor Complex",
      eventStartDate: "2025-11-16",
      eventStartTime: "18:00",
      eventEndDate: "2025-11-16",
      eventEndTime: "21:00",
      capacity: "24",
      level: "intermediate",
      type: "social",
      priceType: "paid",
      participantFee: "20",
      equipment: "Badminton racket, shuttlecocks, court shoes",
      isPrivate: false,
      isRecurring: true,
    },
    {
      id: 19,
      name: "Bootcamp Challenge",
      image:
        "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=400&h=400&fit=crop",
      banner:
        "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=1200&h=400&fit=crop",
      group: "Fit Force",
      sport: "Bootcamp",
      start: "04 Nov 25",
      end: "04 Nov 25",
      created: "19 Sept 25",
      club: "Hardcore Fitness",
      eventStyle: "Intense",
      sportGroup: "Strength & Conditioning",
      sportName: "HIIT",
      facility: "Outdoor Training Ground",
      salon: "",
      eventLocation: "Park Field, North Section",
      eventStartDate: "2025-11-04",
      eventStartTime: "06:00",
      eventEndDate: "2025-11-04",
      eventEndTime: "07:00",
      capacity: "40",
      level: "intermediate",
      type: "training",
      priceType: "paid",
      participantFee: "30",
      equipment: "Training mat, water, towel, athletic wear",
      isPrivate: false,
      isRecurring: true,
    },
    {
      id: 20,
      name: "Skateboarding Workshop",
      image:
        "https://images.unsplash.com/photo-1547447134-cd3f5c716030?w=400&h=400&fit=crop",
      banner:
        "https://images.unsplash.com/photo-1547447134-cd3f5c716030?w=1200&h=400&fit=crop",
      group: "Street Riders",
      sport: "Skateboarding",
      start: "19 Nov 25",
      end: "19 Nov 25",
      created: "05 Oct 25",
      club: "Urban Skate Academy",
      eventStyle: "Street",
      sportGroup: "Extreme Sports",
      sportName: "Skateboarding",
      facility: "Skate Park Central",
      salon: "",
      eventLocation: "Downtown Skate Park, Main Bowl",
      eventStartDate: "2025-11-19",
      eventStartTime: "15:00",
      eventEndDate: "2025-11-19",
      eventEndTime: "18:00",
      capacity: "25",
      level: "beginner",
      type: "workshop",
      priceType: "free",
      participantFee: "",
      equipment: "Skateboard, helmet, knee pads, elbow pads",
      isPrivate: false,
      isRecurring: false,
    },
    {
      id: 21,
      name: "Rowing Competition",
      image:
        "https://images.unsplash.com/photo-1593784991095-a205069470b6?w=400&h=400&fit=crop",
      banner:
        "https://images.unsplash.com/photo-1593784991095-a205069470b6?w=1200&h=400&fit=crop",
      group: "River Racers",
      sport: "Rowing",
      start: "25 Nov 25",
      end: "25 Nov 25",
      created: "08 Oct 25",
      club: "Riverside Rowing Club",
      eventStyle: "Competitive",
      sportGroup: "Water Sports",
      sportName: "Rowing",
      facility: "River Sports Center",
      salon: "",
      eventLocation: "City River, Rowing Lane 1-4",
      eventStartDate: "2025-11-25",
      eventStartTime: "08:00",
      eventEndDate: "2025-11-25",
      eventEndTime: "14:00",
      capacity: "80",
      level: "advanced",
      type: "competition",
      priceType: "paid",
      participantFee: "60",
      equipment: "Rowing suit, water bottle, sunscreen",
      isPrivate: false,
      isRecurring: false,
    },
    {
      id: 22,
      name: "Table Tennis Tournament",
      image:
        "https://images.unsplash.com/photo-1534158914592-062992fbe900?w=400&h=400&fit=crop",
      banner:
        "https://images.unsplash.com/photo-1534158914592-062992fbe900?w=1200&h=400&fit=crop",
      group: "Ping Pong Pros",
      sport: "Table Tennis",
      start: "13 Nov 25",
      end: "13 Nov 25",
      created: "27 Sept 25",
      club: "Table Tennis Association",
      eventStyle: "Fast Paced",
      sportGroup: "Racket Sports",
      sportName: "Table Tennis",
      facility: "Sports Complex",
      salon: "Hall B",
      eventLocation: "990 Sports Boulevard, Hall B",
      eventStartDate: "2025-11-13",
      eventStartTime: "10:00",
      eventEndDate: "2025-11-13",
      eventEndTime: "18:00",
      capacity: "32",
      level: "intermediate",
      type: "tournament",
      priceType: "paid",
      participantFee: "25",
      equipment: "Table tennis paddle, indoor shoes, water",
      isPrivate: false,
      isRecurring: false,
    },
    {
      id: 23,
      name: "Kickboxing Bootcamp",
      image:
        "https://images.unsplash.com/photo-1549719386-74dfcbf7dbed?w=400&h=400&fit=crop",
      banner:
        "https://images.unsplash.com/photo-1549719386-74dfcbf7dbed?w=1200&h=400&fit=crop",
      group: "Strike Force",
      sport: "Kickboxing",
      start: "09 Nov 25",
      end: "09 Nov 25",
      created: "23 Sept 25",
      club: "Combat Fitness Center",
      eventStyle: "High Intensity",
      sportGroup: "Combat Sports",
      sportName: "Kickboxing",
      facility: "Fight Club Gym",
      salon: "Training Area 1",
      eventLocation: "1234 Combat Street, Main Gym",
      eventStartDate: "2025-11-09",
      eventStartTime: "17:00",
      eventEndDate: "2025-11-09",
      eventEndTime: "18:30",
      capacity: "25",
      level: "intermediate",
      type: "training",
      priceType: "paid",
      participantFee: "35",
      equipment: "Hand wraps, boxing gloves, shin guards, mouthguard",
      isPrivate: false,
      isRecurring: true,
    },
    {
      id: 24,
      name: "Archery Beginners Class",
      image:
        "https://images.unsplash.com/photo-1614963323974-4b8a7e0d0b4f?w=400&h=400&fit=crop",
      banner:
        "https://images.unsplash.com/photo-1614963323974-4b8a7e0d0b4f?w=1200&h=400&fit=crop",
      group: "Bullseye Club",
      sport: "Archery",
      start: "17 Nov 25",
      end: "17 Nov 25",
      created: "02 Oct 25",
      club: "Precision Archery Academy",
      eventStyle: "Precision",
      sportGroup: "Target Sports",
      sportName: "Archery",
      facility: "Archery Range",
      salon: "Indoor Range",
      eventLocation: "2468 Arrow Lane, Range Building",
      eventStartDate: "2025-11-17",
      eventStartTime: "13:00",
      eventEndDate: "2025-11-17",
      eventEndTime: "15:00",
      capacity: "15",
      level: "beginner",
      type: "workshop",
      priceType: "paid",
      participantFee: "40",
      equipment: "Bow and arrows (provided), arm guard, finger tab",
      isPrivate: false,
      isRecurring: true,
    },
    {
      id: 25,
      name: "Surfing Lessons",
      image:
        "https://images.unsplash.com/photo-1502680390469-be75c86b636f?w=400&h=400&fit=crop",
      banner:
        "https://images.unsplash.com/photo-1502680390469-be75c86b636f?w=1200&h=400&fit=crop",
      group: "Wave Riders",
      sport: "Surfing",
      start: "23 Nov 25",
      end: "23 Nov 25",
      created: "10 Oct 25",
      club: "Ocean Surf School",
      eventStyle: "Adventure",
      sportGroup: "Water Sports",
      sportName: "Surfing",
      facility: "",
      salon: "",
      eventLocation: "Sunset Beach, Main Break Area",
      eventStartDate: "2025-11-23",
      eventStartTime: "09:00",
      eventEndDate: "2025-11-23",
      eventEndTime: "12:00",
      capacity: "12",
      level: "beginner",
      type: "training",
      priceType: "paid",
      participantFee: "70",
      equipment: "Surfboard (provided), wetsuit, wax, leash",
      isPrivate: false,
      isRecurring: true,
    },
  ];

  const calendarEvents = [
    { day: 1, label: "H13", color: "bg-green-400" },
    { day: 2, label: "Con", color: "bg-blue-600" },
    { day: 3, label: "ICT Expo 2", color: "bg-cyan-400" },
    { day: 13, label: "Dim", color: "bg-cyan-400" },
    { day: 14, label: "A1", color: "bg-yellow-400" },
    { day: 16, label: "Conf", color: "bg-teal-500" },
    { day: 29, label: "Sum", color: "bg-cyan-400" },
  ];

  return (
    <div className="flex h-screen bg-gray-50 overflow-hidden">
      <LeftSidebar isOpen={leftSidebarOpen} />

      {/* Main Content */}
      <div className="flex-1 overflow-auto">
        <Header
          onLeftSidebarToggle={() => setLeftSidebarOpen(!leftSidebarOpen)}
          onRightSidebarToggle={() => setRightSidebarOpen(!rightSidebarOpen)}
        />

        <div className="p-6">
          <div className="bg-gradient-to-r from-orange-50 to-blue-50 rounded-lg p-8 mb-6 flex items-center justify-between">
            <div>
              <h2 className="text-2xl font-bold text-gray-800 mb-2">
                Good admin theme
              </h2>
              <p className="text-gray-600 mb-4">is a tool of enthusiasm</p>
              <button className="bg-red-500 hover:bg-red-600 text-white px-6 py-2 rounded-lg transition-colors">
                Create App
              </button>
            </div>
            <div className="hidden md:block">
              <img
                src="/api/placeholder/300/150"
                alt="Illustration"
                className="w-80"
              />
            </div>
          </div>

          <EventsTable
            events={events}
            activeTab={activeTab}
            setActiveTab={setActiveTab}
            typeFilter={typeFilter}
            setTypeFilter={setTypeFilter}
            sortFilter={sortFilter}
            setSortFilter={setSortFilter}
          />
        </div>
      </div>

      <RightSidebar
        isOpen={rightSidebarOpen}
        currentDate={currentDate}
        setCurrentDate={setCurrentDate}
        calendarView={calendarView}
        setCalendarView={setCalendarView}
        calendarEvents={calendarEvents}
      />

      {/* Mobile Menu Toggle */}
      <button
        onClick={() => setLeftSidebarOpen(!leftSidebarOpen)}
        className="fixed bottom-6 left-6 lg:hidden bg-cyan-500 text-white p-3 rounded-full shadow-lg z-50"
      >
        {leftSidebarOpen ? (
          <X className="w-6 h-6" />
        ) : (
          <Menu className="w-6 h-6" />
        )}
      </button>

      <button
        onClick={() => setRightSidebarOpen(!rightSidebarOpen)}
        className="fixed bottom-6 right-6 lg:hidden bg-cyan-500 text-white p-3 rounded-full shadow-lg z-50"
      >
        {rightSidebarOpen ? (
          <X className="w-6 h-6" />
        ) : (
          <Calendar className="w-6 h-6" />
        )}
      </button>
    </div>
  );
};

export default EventsDashboard;
